version: '3.8'

services:
  nginx:
    build:  
      context: ./nginx 
    ports:
      - "80:80" 
    depends_on:
      - python-app  
    networks:
      - app-network

  python-app:
    build:  
      context: ./Python  
    container_name: python_app
    expose:
      - "8000"  
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
